lib/elixir_microservice_web/router.ex
defmodule ElixirMicroserviceWeb.Router do
  use ElixirMicroserviceWeb, :router

  import ElixirMicroserviceWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ElixirMicroserviceWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirMicroserviceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:elixir_microservice, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ElixirMicroserviceWeb.Telemetry, ecto_repos: [ElixirMicroservice.Repo]
    end
  end

  ## Authentication routes

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/elixir_microservice_web/views/layout_view.ex
defmodule ElixirMicroserviceWeb.LayoutView do
  use ElixirMicroserviceWeb, :view
end

lib/elixir_microservice_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
  <%= @current_user.email %>
  <%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %>
  <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %>
<% else %>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %>
<% end %>

lib/elixir_microservice_web/templates/layout/app.html.heex
<main role="main" class="container mx-auto max-w-4xl px-4 lg:px-0">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/elixir_microservice_web/templates/layout/live.html.heex
<main role="main" class="container mx-auto max-w-4xl px-4 lg:px-0">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/elixir_microservice_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" data-theme="light" class="h-full bg-base-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "ElixirMicroservice", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="flex flex-col h-full pt-24 text-base-content">
    <header class="fixed top-0 left-0 right-0 z-30 px-2 py-4 shadow bg-base-100 sm:px-4">
      <div class="container flex items-center justify-between mx-auto">
        <a href="/" title="ElixirMicroservice Home Page" class="flex items-center text-xl text-base-content text-opacity-80">
          ElixirMicroservice
        </a>
        <div class="flex items-center space-x-1">
          <div class="hidden md:inline-flex space-x-1">
            <%= link "Home", to: Routes.page_path(@conn, :index), class: "btn btn-sm btn-link" %>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn btn-sm btn-link" %>
            <% end %>
          </div>
          <%= render "_user_menu.html", assigns %>
          <div class="inline-flex md:hidden" x-data="{ open: false }">
            <button class="flex-none px-2 btn btn-link btn-sm" @click="open = true">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
                >
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
              </svg>
              <span class="sr-only">Open Menu</span>
            </button>
            <div class="absolute top-0 left-0 right-0 z-50 flex flex-col p-2 pb-4 m-2 rounded shadow-xl bg-base-200 space-y-3" x-show.transition="open" @click.away="open = false" x-cloak>
              <button class="self-end flex-none px-2 ml-2 btn btn-link btn-icon" @click="open = false">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  aria-hidden="true"
                  >
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
                <span class="sr-only">Close Menu</span>
              </button>
              <%= link "Home", to: Routes.page_path(@conn, :index), class: "btn btn-link w-full" %>
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn btn-link w-full" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>

    <%= @inner_content %>

    <footer class="py-3 mt-auto bg-gray-800">
      <div class="container max-w-4xl pb-4 mx-auto text-sm text-center text-gray-300">
        &copy; <%= DateTime.utc_now.year %> ElixirMicroservice
      </div>
    </footer>
  </body>
</html>

lib/elixir_microservice_web/templates/layout/session.html.heex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "ElixirMicroservice", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="flex flex-col h-full pt-20 bg-gray-200 dark:bg-gray-800 sm:pt-24">
    <main role="main" class="container max-w-6xl px-4 mx-auto mb-8">
      <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="flex max-w-sm mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 lg:max-w-4xl">
        <div class="hidden bg-cover lg:block lg:w-1/2" style="background-image:url('https://images.unsplash.com/photo-1602610411365-76e8c2a88e18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=333&q=80')"></div>

        <div class="w-full px-6 py-8 md:px-8 lg:w-1/2">
          <h2 class="text-2xl font-semibold text-center text-gray-700 dark:text-white">ElixirMicroservice</h2>
          <%= @inner_content %>
        </div>
      </div>
    </main>
  </body>
</html>