lib/elixir_microservice_web/router.ex
defmodule ElixirMicroserviceWeb.Router do
  use ElixirMicroserviceWeb, :router

  import ElixirMicroserviceWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ElixirMicroserviceWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirMicroserviceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:elixir_microservice, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ElixirMicroserviceWeb.Telemetry, ecto_repos: [ElixirMicroservice.Repo]
    end
  end

  ## Authentication routes

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ElixirMicroserviceWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/elixir_microservice_web/controllers/user_registration_controller.ex
defmodule ElixirMicroserviceWeb.UserRegistrationController do
  use ElixirMicroserviceWeb, :controller

  alias ElixirMicroservice.Accounts
  alias ElixirMicroservice.Accounts.User
  alias ElixirMicroserviceWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/elixir_microservice_web/views/user_registration_view.ex
defmodule ElixirMicroserviceWeb.UserRegistrationView do
  use ElixirMicroserviceWeb, :view
end

lib/elixir_microservice_web/templates/user_registration/new.html.heex
<h3 class="text-xl text-center text-gray-600 dark:text-gray-200">Register</h3>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="mt-4">
    <%= label f, :email, class: "block text-gray-600 dark:text-gray-200 text-sm font-medium mb-2" %>
    <%= text_input f, :email, required: true, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="mt-4">
    <div class="flex justify-between">
      <%= label f, :password, class: "block text-gray-600 dark:text-gray-200 text-sm font-medium mb-2" %>
      <%= link "Forgot password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-xs text-gray-500 dark:text-gray-300 hover:underline" %>
    </div>

    <%= password_input f, :password, required: true, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="mt-8">
    <%= submit "Register", class: "btn btn-primary w-full" %>
  </div>
</.form>

<div class="flex items-center justify-between mt-6">
  <span class="w-1/5 border-b dark:border-gray-600 md:w-1/4"></span>

  <%= link "Or Log in", to: Routes.user_session_path(@conn, :new), class: "text-xs text-gray-500 dark:text-gray-400 uppercase hover:underline" %>

  <span class="w-1/5 border-b dark:border-gray-600 md:w-1/4"></span>
</div>